version: '3.5'
services:

  clients-api:
    container_name: clients-api
    image: clients_api:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DATASOURCE_URL: ${DATASOURCE_URL}
    ports:
      - "8081:8081"
    networks:
      - pismo-network
    restart: unless-stopped

networks:
  pismo-network:
    external: true